# Generated by Django 3.2.6 on 2021-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_share',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Статья', 'Статья'), ('Новость', 'Новость')], default='Статья', max_length=16),
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='simpleapp.PostCategory', to='simpleapp.Category'),
        ),
    ]
